engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
- doc/**
